
MICROSTEPS_HORIZONTAL = 8
STEPS_IN_HORIZONTAL_REVOLUTION = 200
STEPS_IN_QUATER_ROTATION = STEPS_IN_HORIZONTAL_REVOLUTION // 4
MICROSTEPS_IN_QUATER_ROTATION = STEPS_IN_QUATER_ROTATION * MICROSTEPS_HORIZONTAL

MICROSTEPS_VERTICAL = 1
STEPS_IN_VERTICAL_REVOLUTION = 200
REVOUTIONS_IN_FLOOR = 30
STEPS_IN_FLOOR = STEPS_IN_VERTICAL_REVOLUTION * REVOUTIONS_IN_FLOOR
MICROSTEPS_IN_FLOOR = STEPS_IN_FLOOR * MICROSTEPS_VERTICAL

DELAY_VERTICAL = 500 * 1e-6
DELAY_HORIZONTAL = 2000 * 1e-6

MOTOR_VERTICAL1_PULSE = 5
MOTOR_VERTICAL1_DIRECTION = 6
MOTOR_VERTICAL2_PULSE = 23
MOTOR_VERTICAL2_DIRECTION = 24
MOTOR_VERTICAL3_PULSE = 20
MOTOR_VERTICAL3_DIRECTION = 21

MOTOR_HORIZONTAL_PULSE = 17
MOTOR_HORIZONTAL_DIRECTION = 27

FORWARD_STOP_DISTANCE = 4
BACKWARD_STOP_DISTANCE = FORWARD_STOP_DISTANCE

LEFT_MOTOR_SPEED = 63
RIGHT_MOTOR_SPEED = 63